/*
  Auto-generated by Spline
*/

import useSpline from '@splinetool/r3f-spline'
import { PerspectiveCamera } from '@react-three/drei'

export default function Scene({ ...props }) {
  const { nodes, materials } = useSpline('https://prod.spline.design/RlGf0SBK5pkSy-nY/scene.splinecode')
  return (
    <>

      <group {...props} dispose={null}>
        <mesh
          name="Sphere"
          geometry={nodes.Sphere.geometry}
          material={materials['Sphere Material']}
          castShadow
          receiveShadow
          position={[-71, 467.15, 39]}
        />
        <group name="Group" position={[156, 0, 0]} rotation={[0, 0, -0.14]}>
          <mesh
            name="Cube"
            geometry={nodes.Cube.geometry}
            material={materials['Cube Material']}
            castShadow
            receiveShadow
            position={[1.52, 21.71, 0]}
            rotation={[0, 0, -0.14]}
          />
        </group>

      </group>
    </>
  )
}
